import Head from "next/head";
import { Biography, Hero, Banner, SecondSection, Testimonial } from "../src/components/Home";
import { Button, Footer } from "../src/components/Shared";
import Header from '../src/components/Shared/Header'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Lisa Marie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Playfair+Display+SC:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <Hero />
      <Banner extraClasses="flex items-center justify-center bg-red-400 h-52">
        <div className="sm:w-4/12 w-8/12 h-full flex flex-col justify-evenly items-center">
          <strong className="text-center font-playfair">
            This is a content of the banner
          </strong>
          <Button text="Go to xyz now" extraClasses="h-10" />
        </div>
      </Banner>
      <SecondSection />
      <Banner extraClasses="bg-red-500 h-72 flex  justify-center">
        <div className="sm:w-4/12 w-8/12 h-full flex flex-col justify-between items-center">
          <strong className="text-center font-playfair">
            This is a content of the banner
          </strong>
          <Button text="Go to xyz now" extraClasses="h-10" />
        </div>
      </Banner>
      {/* <Biography></Biography> */}
      <Testimonial />
      <Footer />
    </div>
  );
}
